/**
 * The gate on the allowlist writer.
 *
 * `update-cf-ranges` is the only thing that ever writes fs-cloudflare's allowlist, and the
 * only thing that ever runs it is a weekly cron on `main` — so without this file its
 * validation branches would reach production unexecuted. Each one is asserted against the
 * body it exists to reject (an HTML error page, a truncated response, a 5xx), not merely
 * against today's happy path: a validator that only ever sees valid input cannot be told
 * apart from no validator at all.
 */
import {readFileSync} from 'node:fs';
import path from 'node:path';
import {describe, expect, it} from 'vitest';

import {buildRangesModule, withoutSnapshotDate} from './update-cf-ranges.core.mjs';

const V4_URL = 'https://www.cloudflare.com/ips-v4';
const V6_URL = 'https://www.cloudflare.com/ips-v6';
const RANGES = path.join(import.meta.dirname, '..', 'packages', 'cloudflare', 'src', 'ranges.ts');

/** A fetch that only knows the urls the test names — anything else is a fetch that drifted. */
const serving = (bodies) => async (url) => {
    const body = bodies[url];
    if (body === undefined) throw new Error(`unexpected fetch of ${url}`);
    return typeof body === 'string' ? {ok: true, text: async () => body} : body;
};

const build = (bodies, snapshot = '2026-01-02') => buildRangesModule({fetch: serving(bodies), snapshot});

describe('buildRangesModule', () => {
    it('should render both endpoints into the vendored module shape', async () => {
        const output = await build({[V4_URL]: '1.2.3.0/24\n5.6.7.0/22\n', [V6_URL]: '2400:cb00::/32\n'});

        // Byte-for-byte: this string IS the file format, indent, quoting and trailing
        // newline included. Anything looser lets a render change land unnoticed and turns
        // the drift workflow's `git diff` permanently red.
        expect(output).toBe(
            `// Cloudflare's published egress ranges, source https://www.cloudflare.com/ips/ (snapshot 2026-01-02).
// Generated by scripts/update-cf-ranges.mjs — do not hand-edit. The scheduled cf-ranges-drift
// workflow re-runs that script weekly and fails when the live endpoints no longer match.
export const CLOUDFLARE_IPV4 = [
    '1.2.3.0/24',
    '5.6.7.0/22',
];

export const CLOUDFLARE_IPV6 = [
    '2400:cb00::/32',
];
`,
        );
    });

    it('should reproduce the committed ranges.ts exactly from its own ranges', async () => {
        // The shell's whole contract: a run against unchanged endpoints must leave the file
        // byte-identical. Fed the vendored ranges back as response bodies, the renderer has
        // to return the vendored file — otherwise every cron run rewrites it and reports drift.
        const vendored = readFileSync(RANGES, 'utf8');
        const rangesIn = (name) => {
            const opener = `export const ${name} = [\n`;
            const body = vendored.slice(vendored.indexOf(opener) + opener.length);
            return (
                body
                    .slice(0, body.indexOf('];'))
                    .trim()
                    .split('\n')
                    // `    '1.2.3.0/24',` -> `1.2.3.0/24`
                    .map((line) => line.trim().slice(1, -2))
                    .join('\n')
            );
        };

        const output = await build(
            {[V4_URL]: rangesIn('CLOUDFLARE_IPV4'), [V6_URL]: rangesIn('CLOUDFLARE_IPV6')},
            vendored.match(/\(snapshot (\d{4}-\d{2}-\d{2})\)/)[1],
        );

        expect(output).toBe(vendored);
    });

    it('should refuse a non-ok response instead of writing an error page', async () => {
        await expect(
            build({
                [V4_URL]: {ok: false, status: 503, statusText: 'Service Unavailable', text: async () => 'nope'},
                [V6_URL]: '2400:cb00::/32',
            }),
        ).rejects.toThrow('https://www.cloudflare.com/ips-v4 responded 503 Service Unavailable');
    });

    it('should refuse an empty or whitespace-only body', async () => {
        // A 200 with nothing in it would otherwise render an empty allowlist — a gate that
        // 403s every visitor.
        await expect(build({[V4_URL]: '', [V6_URL]: '2400:cb00::/32'})).rejects.toThrow(
            'https://www.cloudflare.com/ips-v4 returned no ranges',
        );
        await expect(build({[V4_URL]: '1.2.3.0/24', [V6_URL]: '  \n\n '})).rejects.toThrow(
            'https://www.cloudflare.com/ips-v6 returned no ranges',
        );
    });

    it('should reject non-CIDR entries and name every offender', async () => {
        await expect(
            build({[V4_URL]: '<html>\n<body>error</body>\n1.2.3.0/24\n', [V6_URL]: '2400:cb00::/32'}),
        ).rejects.toThrow(
            'https://www.cloudflare.com/ips-v4 returned 2 entries that are not CIDR ranges: <html>, <body>error</body>',
        );

        // A bare address is not a range: admitted unvalidated it would widen or void the gate.
        await expect(build({[V4_URL]: '1.2.3.0/24', [V6_URL]: '2400:cb00::/32\n2606:4700::'})).rejects.toThrow(
            'https://www.cloudflare.com/ips-v6 returned 1 entries that are not CIDR ranges: 2606:4700::',
        );
    });
});

describe('withoutSnapshotDate', () => {
    it('should ignore the date but never the ranges', async () => {
        const bodies = {[V4_URL]: '1.2.3.0/24', [V6_URL]: '2400:cb00::/32'};
        const monday = await build(bodies, '2026-01-02');
        const tuesday = await build(bodies, '2026-01-03');
        const changed = await build({...bodies, [V4_URL]: '1.2.3.0/24\n9.9.9.0/24'}, '2026-01-02');

        expect(withoutSnapshotDate(monday)).toBe(withoutSnapshotDate(tuesday));
        expect(monday).not.toBe(tuesday);
        expect(withoutSnapshotDate(changed)).not.toBe(withoutSnapshotDate(monday));
    });
});
