/**
 * Range-refresh decision logic — the whole of it, with no I/O.
 *
 * Split out of `update-cf-ranges.mjs` the same way `detect-publishable.core.mjs` was, and
 * for the same reason: this module is the sole writer of fs-cloudflare's allowlist, yet the
 * only thing that ever runs it is a weekly cron on `main`. Logic left in the shell is logic
 * no PR executes — and a validation branch that never runs is a validation branch that
 * cannot be trusted to reject an HTML error page.
 *
 * ── REFUSE, DON'T GUESS ──────────────────────────────────────────────────────────
 * A non-2xx response, an empty body, or a single entry that is not a CIDR throws. The two
 * error directions are not symmetric: aborting costs a red cron run, while writing a
 * half-parsed body either opens the gate to the whole internet or 403s every real visitor.
 */

export const SOURCES = [
    {name: 'CLOUDFLARE_IPV4', url: 'https://www.cloudflare.com/ips-v4', pattern: /^\d{1,3}(\.\d{1,3}){3}\/\d{1,2}$/},
    {name: 'CLOUDFLARE_IPV6', url: 'https://www.cloudflare.com/ips-v6', pattern: /^[\da-f:]+\/\d{1,3}$/},
];

const fetchRanges = async ({url, pattern}, fetchImpl) => {
    const response = await fetchImpl(url);
    if (!response.ok) {
        throw new Error(`${url} responded ${response.status} ${response.statusText}`);
    }

    const body = await response.text();
    const ranges = body
        .split('\n')
        .map((line) => line.trim())
        .filter((line) => line.length > 0);

    if (ranges.length === 0) {
        throw new Error(`${url} returned no ranges`);
    }

    // Named, not counted: a maintainer reading a red cron run needs to see WHAT arrived —
    // an HTML error page and a genuinely new address format need different responses.
    const malformed = ranges.filter((range) => !pattern.test(range));
    if (malformed.length > 0) {
        throw new Error(
            `${url} returned ${malformed.length} entries that are not CIDR ranges: ${malformed.join(', ')}`,
        );
    }

    return ranges;
};

const renderArray = (name, ranges) =>
    `export const ${name} = [\n${ranges.map((range) => `    '${range}',`).join('\n')}\n];\n`;

const render = (rendered, snapshot) =>
    [
        `// Cloudflare's published egress ranges, source https://www.cloudflare.com/ips/ (snapshot ${snapshot}).`,
        '// Generated by scripts/update-cf-ranges.mjs — do not hand-edit. The scheduled cf-ranges-drift',
        '// workflow re-runs that script weekly and fails when the live endpoints no longer match.',
        '',
    ].join('\n') + rendered.join('\n');

/** The full `ranges.ts` source for the live endpoints, or a throw. Never returns a partial module. */
export const buildRangesModule = async ({fetch: fetchImpl, snapshot}) => {
    const arrays = [];
    for (const source of SOURCES) {
        arrays.push(renderArray(source.name, await fetchRanges(source, fetchImpl)));
    }
    return render(arrays, snapshot);
};

// The date is the only part of the file that is not a function of the endpoints; ignore it when
// deciding whether anything actually changed. Without this the module would be rewritten on every
// run and the drift workflow's `git diff` would report drift every week, teaching its reader to
// ignore it.
export const withoutSnapshotDate = (source) => source.replace(/\(snapshot \d{4}-\d{2}-\d{2}\)/, '(snapshot)');
